buildAndroid:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: build
  cache:
    paths:
      - node_modules
      - cordova/node_modules
  before_script:
    - PATH=$PATH:/opt/gradle-5.6/bin
    - npm install --dev
    - cd cordova
    - cordova platform add android
    - cd ..
  script:
    - npm run build-android
    - cd cordova
    - echo "org.gradle.daemon=true\n" >> platforms/android/gradle.properties
    - echo "org.gradle.jvmargs=-Xmx3072m\n" >> platforms/android/gradle.properties
    - echo "android.useDeprecatedNdk=true\n" >> platforms/android/gradle.properties
    - cordova build android --release
  after_script:
    - cp -r cordova/platforms/android/build android-build
  artifacts:
    paths:
      - android-build
    name: "android-build-$CI_COMMIT_REF_NAME"
  only:
    - develop
    - master