buildAndroid:
  image: posohof/android:latest
  stage: build
  services:
    - node
  cache:
    paths:
      - node_modules
      - cordova/node_modules
  before_script:
    - npm install --dev
    - cd cordova
    - npm install -g cordova
    - cordova platform add electron
    - cd ..
  script:
    - npm run build-android
    - cd cordova
    - cordova build android --release
  after_script:
    - cp -r cordova/platforms/android/build android-build
  artifacts:
    paths:
      - android-build
    name: "android-build-$CI_COMMIT_REF_NAME"
  only:
    - develop
    - master