prepareAndroid:
  image: node
  stage: prepare
  cache:
    paths:
      - node_modules
      - cordova/node_modules
  before_script:
    - npm install --dev
    - cd cordova
    - npm install -g cordova
    - cd ..
  script:
    - npm run build-android
    - cd cordova
    - cordova prepare android
    - cd ..
  after_script:
    - cp -r cordova/platforms/android/ android-build
  artifacts:
    paths:
      - android-build
  only:
    - develop
    - master