stages:
  - build
  - test
  - deploy

buildWeb:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
  before_script:
    - npm install --dev
  script:
    - npm run build-web
  artifacts:
    paths:
      - dist
  only:
    - develop
    - master
