image: node

variables:
  NODE_ENV: production
  AWS_DEFAULT_REGION: eu-west-3
  BUCKET_NAME: steapp

before_script:
  - npm install --dev

stages:
  - build
  - deploy

buildNuxt:
  stage: build
  script:
    - npm run build
  artifacts:
    name: "client"
    paths:
      - public
  only: 
    - master

deploys3:
  image: "python:latest"
  stage: deploy
  dependencies:
    - buildNuxt
  before_script:
    - pip install awscli
  script:
    - aws s3 cp public s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  only: 
    - master
  when: manual

