image: node:latest

variables:
  NODE_ENV: production
  AWS_DEFAULT_REGION: eu-west-3
  BUCKET_NAME: steapp

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

buildNuxt:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only: 
    - master

deploys3:
  image: "python:latest"
  stage: deploy
  dependencies:
    - buildNuxt
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  only: 
    - master
  when: manual
