stages:
  - build
  - test
  - deploy

buildWeb:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
  before_script:
    - npm install --dev
  script:
    - npm run build-web
  after_script:
    - cp -r dist web-build
  artifacts:
    paths:
      - web-build
    name: "web-build-$CI_COMMIT_REF_NAME"
  only:
    - develop
    - master

buildAndroid:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
      - cordova/node_modules
  before_script:
    - npm install --dev
    - cd cordova
    - npm install -g cordova
    - cordova platform add android
    - cd ..
  script:
    - npm run build-android
  only:
    - develop
    - master

buildPanel:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
      - cordova/node_modules
  before_script:
    - npm install --dev
    - cd cordova
    - npm install -g cordova
    - cordova platform add electron
    - cd ..
  script:
    - npm run build-panel
  after_script:
    - cp -r cordova/platforms/electron/build/linux-arm64-unpacked/ panel-build
  artifacts:
    paths:
      - panel-build
    name: "panel-build-$CI_COMMIT_REF_NAME"
  only:
    - develop
    - master