image: node

variables:
  NODE_ENV: production
  AWS_DEFAULT_REGION: eu-west-3
  BUCKET_NAME: steapp
  
cache:
  paths:
    - node_modules

before_script:
  - npm install

stages:
  - build
  - deploy

buildNuxt:
  stage: build
  script:
    - npm run build
  artifacts:
    name: "client"
    paths:
      - public
  only: 
    - develop
    - master
    - tags

deployRelease:
  image: "python:latest"
  stage: deploy
  dependencies:
    - buildNuxt
  before_script:
    - pip install awscli
  script:
    - tar -cvf client-${CI_COMMIT_TAG}.zip public/
    - aws s3 cp client-${CI_COMMIT_TAG}.zip s3://${BUCKET_NAME}/client/
  only: 
    - tags
