stages:
  - build
  - test
  - deploy

buildWeb:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
  before_script:
    - npm install --dev
  script:
    - npm run build-web
  after_script:
    - cp dist build-web
  artifacts:
    paths:
      - build-web
  only:
    - develop
    - master

buildPanel:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
      - cordova/node_modules
  before_script:
    - npm install --dev
    - cd cordova
    - npm install -g cordova
    - cordova platform add electron
    - cd ..
  script:
    - npm run build-panel
  after_script:
    - cp cordova/platforms/electron/build/ panel-build
  artifacts:
    paths:
      - panel-build
  only:
    - develop
    - master