buildPanel:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
      - cordova/node_modules
  before_script:
    - npm install --dev
    - cd cordova
    - npm install -g cordova
    - cordova platform add electron
    - cd ..
  script:
    - npm run build-panel
  after_script:
    - cp -r cordova/platforms/electron/build/linux-arm64-unpacked/ panel-build
  artifacts:
    paths:
      - panel-build
    name: "panel-build-${CI_COMMIT_REF_NAME}"
  only:
    - develop
    - master

deployPanelDevelop:
  image: python:latest
  stage: deploy
  needs: [buildPanel]
  before_script:
    - pip install awscli
  script:
    - python -m zipfile -c panel-build.zip panel-build/
    - aws s3 cp panel-build.zip s3://${BUCKET_NAME}/steapp/panel/testing/
  only:
    - develop