buildWeb:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
  before_script:
    - npm install --dev
  script:
    - npm run build-web
  after_script:
    - cp -r dist web-build
  artifacts:
    paths:
      - web-build
    name: "web-build-${CI_COMMIT_REF_NAME}"
  only:
    - develop
    - master

deployWebDevelop:
  image: brentley/awscli:latest
  stage: deploy
  needs: [buildWeb]
  script:
    - aws s3 help
    - aws s3 cp web-build/ s3://${BUCKET_NAME}/steapp/testing/${CI_COMMIT_SHORT_SHA} --recursive
  environment:
    name: testing
    url: http://${BUCKET_NAME}/steapp/testing/${CI_COMMIT_SHORT_SHA}
    on_stop: cleanWebDevelop
  only:
    - develop

cleanWebDevelop:
  image: brentley/awscli:latest
  stage: deploy
  script:
    - aws s3 rm s3://${BUCKET_NAME}/steapp/testing/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: testing
    action: stop
  when: manual
