buildWeb:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
  before_script:
    - npm install --dev
  script:
    - npm run build-web
  after_script:
    - cp -r dist web-build
  artifacts:
    paths:
      - web-build
    name: "web-build-${CI_COMMIT_REF_NAME}"
  only:
    - develop
    - master

deployWebDevelop:
  image: python:latest
  stage: deploy
  needs: [buildWeb]
  before_script:
    - pip install awscli
  script:
    - python -m zipfile -c web-build.zip web-build/
    - aws s3 cp web-build.zip s3://${BUCKET_NAME}/steapp/web/testing/
  environment:
    name: testing
    url: https://s3.eu-west-3.amazonaws.com/${BUCKET_NAME}/steapp/web/testing
    on_stop: cleanWebDevelop
  only:
    - develop

cleanWebDevelop:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - python -m zipfile -c web-build.zip web-build/
    - aws s3 rm s3://${BUCKET_NAME}/steapp/web/testing/web-build.zip
  environment:
    name: testing
    action: stop
  when: manual
