prepareWeb:
  stage: prepare
  script:
    - echo "Prepare build web app"
  only:
    - develop
    - master

buildWeb:
  image: node
  stage: build
  needs: [prepareWeb]
  cache:
    paths:
      - node_modules
  before_script:
    - npm install --dev
  script:
    - npm run build-web
  after_script:
    - cp -r dist web-build
  artifacts:
    paths:
      - web-build
    name: "web-build-$CI_COMMIT_REF_NAME"
  only:
    - develop
    - master