name: Android App CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: posohof/android:latest
    env:
      USE_HARD_LINKS: 'false'
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 10.x
        
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: Run npm preparation script
        run: | 
          npm ci --cache .npm --prefer-offline
          cd cordova
          npm install -g cordova
          cordova platform add android
          cd ..
      
      - name: Build Android App
        run: npm run build-android
      
      - name: Copy resources
        run: |
          cd cordova
          cp keystore.jks platforms/android/app/keystore.jks
          cordova build android --release -- --keystore=keystore.jks --storePassword=${{secrets.ANDROID_STORE_PASSWORD}} --alias=upload --password=${{secrets.ANDROID_PASSWORD}} --gradleArg=-PcdvVersionCode=$(date --date="-18 year" +%-g%m%d%H0)
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: android-build
          path: cordova/platforms/android/app/build/output
