
name: Web App CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:10.17.0-alpine
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: Run npm preparation script
        run: npm ci --cache .npm --prefer-offline
      
      - name: Build web App
        run: npm run build-web
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: web-build
          path: dist
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      RELEASE_TYPE: testing
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: web-build
        
      - uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: web-build.zip
          
      - name: Set release type
        run: echo "RELEASE_TYPE=stable" >> $GITHUB_ENV
        if: github.ref == 'master'
          
      - uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 cp web-build.zip s3://${{ secrets.BUCKET_NAME }}/steapp/web/${{ env.RELEASE_TYPE }}/ --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}      
